#docker container kill $(docker container ls -a -q)
#docker rm $(docker container ls -a -q)
#docker rmi $(docker images -q)
#docker container kill $(docker container ls -a -q); docker rm $(docker container ls -a -q); docker rmi $(docker images -q)

version: '3.7'

services:
  femr-app:
    container_name: femr-app
    build:
      context: ./femrApp
    ports:
      - 9000:9000
    env_file:
      - ./env
    volumes:
      - ./appData:/opt/femr
  db:
    container_name: db
    image: mysql:5.7.27
    env_file:
      - ./env
    volumes:
      - ./dbData:/var/lib/mysql
# volumes:
#   dbData:
#   appData: